"""empty message

Revision ID: 9d9f91cd7c27
Revises: 53b1a35ce91a
Create Date: 2022-07-22 21:28:33.716245

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9d9f91cd7c27'
down_revision = '53b1a35ce91a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog_post', sa.Column('downvotes', sa.Integer(), nullable=True))
    op.alter_column('blog_post', 'pub_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_post', 'pub_date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_column('blog_post', 'downvotes')
    # ### end Alembic commands ###
